# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7267edb5f829bdc389771b239cdc890cf23a3d5408bc38ee98796253e45f0d75eb21040e10e854001e3c714a2428f08bd08c5f98e18e1b615da9062c13a46ac0

test:
  secret_key_base: e0f5e6cb85079134f587e8f226c8318fd9b79d8862bb870e410bc9606fc6a52b8f8438b1008fdd86482ddf7c36eb2a7c2278544435758d00ed18a11876ba315d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
